import React, { useState } from 'react';
import { Header, InputForm, NameCard, LoadingState } from './components/Layout';
import { generateNameSuggestions } from './services/geminiService';
import { NameSuggestion, SourceText } from './types';
import { AlertCircle } from 'lucide-react';

const App: React.FC = () => {
  const [description, setDescription] = useState('');
  const [source, setSource] = useState<SourceText>(SourceText.ALL);
  const [results, setResults] = useState<NameSuggestion[] | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    if (!description.trim()) return;

    setIsGenerating(true);
    setError(null);
    setResults(null);

    try {
      const suggestions = await generateNameSuggestions(description, source);
      setResults(suggestions);
    } catch (err) {
      setError("Failed to generate names. Please ensure the API key is configured or try again later.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#fffaf0] pb-20">
      <Header />
      
      <main className="container mx-auto px-4 relative z-10">
        
        {/* Input Section */}
        <section className="mb-16">
          <InputForm
            description={description}
            source={source}
            isGenerating={isGenerating}
            onDescriptionChange={setDescription}
            onSourceChange={setSource}
            onSubmit={handleSubmit}
          />
        </section>

        {/* Error Message */}
        {error && (
          <div className="max-w-2xl mx-auto mb-10 bg-red-50 border border-red-200 rounded-lg p-4 flex items-center gap-3 text-red-800">
            <AlertCircle className="w-5 h-5 flex-shrink-0" />
            <p>{error}</p>
          </div>
        )}

        {/* Loading State */}
        {isGenerating && <LoadingState />}

        {/* Results Grid */}
        {results && (
          <section className="animate-fade-in-up">
            <div className="flex items-center gap-4 mb-8">
                <div className="h-px bg-stone-300 flex-grow"></div>
                <h2 className="text-2xl font-serif text-maroon-900 font-bold">
                    Suggested Names
                </h2>
                <div className="h-px bg-stone-300 flex-grow"></div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {results.map((suggestion, index) => (
                <NameCard 
                  key={index} 
                  suggestion={suggestion} 
                  index={index}
                />
              ))}
            </div>

            <div className="mt-12 text-center text-stone-500 text-sm">
                <p>Names are generated by AI and inspired by ancient texts. Please verify cultural context and availability before use.</p>
            </div>
          </section>
        )}
      </main>
    </div>
  );
};

export default App;